[general]
live_config_reload = true
import = [ "dracula.toml" ]
[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "None"
# opacity = 0.9

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size = 15

[cursor]
style = { shape = "Block", blinking = "Always" }